version: '3.7'

services:
  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: trivyal
      POSTGRES_PASSWORD: "ATFqRIyGah8Zu9oANGEGUjawqnQ7fygb"
    volumes:
      - trivyal_data:/var/lib/postgresql/data
volumes:
  trivyal_data:
