name: trivyal_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  rxdart: ^0.28.0
  serverpod: 2.1.5
  serverpod_auth_server: 2.1.5

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
